-- AlterTable
ALTER TABLE "Product" ADD COLUMN     "vatRate" DOUBLE PRECISION NOT NULL DEFAULT 8;

-- AlterTable
ALTER TABLE "Sale" ADD COLUMN     "vat" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "SaleItem" ADD COLUMN     "vatRate" DOUBLE PRECISION NOT NULL DEFAULT 8;

-- AlterTable
ALTER TABLE "TableOrderItem" ADD COLUMN     "vatRate" DOUBLE PRECISION NOT NULL DEFAULT 8;
